### PR TITLE
feat: add sortBy property for pagination options

### PR DESCRIPTION
**Pull request by boredland**
I think you didn't have the sorting properties, so I added them to your PaginationOptions.

https://documenter.getpostman.com/view/799228/absenceio-api-documentation/2Fwbis?version=latest#querying-objects

### CODE REVIEW

**Comment by ffflorian** [comment]
Hi @boredland, thank you for your PR!

Please run

```
yarn
yarn fix
```

in the main directory of your fork once to resolve the linting errors.

**Comment by boredland** [comment]
Oh, sorry. Apparently my workspace rules were applied.

**Comment by ffflorian** [comment]
Thank you :)

**Comment by ffflorian** [comment]
Published in `absence.io@1.2.0` 🎉

**Pull request merged**
